### ISSUE TITLE
Visual Studio 2013 support?

### ISSUE THREAD

**Issue by paul-ferragut** [micuat/ofxPCL#2]
Hi
Thanks for the setup instructions with codeblocks, it was helpful!

Is it not possible to run ofxPCL with VS 2013 or 2012?
(I would like to run ofxPCL with with the kinect V2 add-on only compatible with VS)
Thanks

**Comment by micuat** [comment]
I'm willing to do so, but unfortunately, original PCL only supports VS 2008/2010:
http://pointclouds.org/downloads/windows.html
and that's why I use CB. I saw some discussions going on to support latest VS on the mailing list so I hope they do it soon.

**Comment by paul-ferragut** [comment]
Oh that's too bad.
I found this http://unanancyowen.com/?p=712 maybe useful? as well some users mention they managed to compile it in this thread: http://www.pcl-users.org/PCL-and-Visual-Studio-2013-td4033926.html
I will try if it can work

**Comment by micuat** [comment]
Looks nice. I don't have a Windows environment right now so I'm glad if you can contribute to the repo (preferably PR to the original one github.com/satoruhiga/ofxPCL )

**Comment by paul-ferragut** [comment]
my coding experience is limited. if you have recommendations on the different steps to create the VS add-ons (or useful learning resources) please let me know !

**Comment by micuat** [comment]
I suppose the easiest way (but yet complicated) is to install PCL using his installer and add ofxPCL/src to your project. Also add PCL libraries and header paths, and PCL options as he specifies,
- `PCL_ROOT` : `C:\Program Files\PCL 1.7.2` (or `C:\Program Files (x86)\PCL 1.7.2`)
- `Path` : `;%PCL_ROOT%\bin` `;%PCL_ROOT%\3rdParty\FLANN\bin` `;%PCL_ROOT%\3rdParty\VTK\bin`

**Comment by paul-ferragut** [comment]
Thanks for the help.
I finally managed to compile for VS 2013 without error. however having bug on launch " Debug Assertion Failed Expression: vector subscript out of range"  happening with the downsample function in ofxPCL.h and sor.filter(*cloud);
I will create a fork from the original repo

**Comment by micuat** [comment]
Could you provide me with a whole stack trace?

**Comment by paul-ferragut** [comment]
Hi 
today I tried again using the precompiled libraries found here http://unanancyowen.com/?p=1255&lang=en and it's working fine.
I created a new libs folder :  https://app.box.com/libs-ofxPCL-vs110
I am using OF 08.4 with visual studio 2015 with the toolset v110 (vs 2012 ) 
This are setup instructions for anyone needing  it

-unzip and place folder https://app.box.com/libs-ofxPCL-vs110 pcl in ofxPCL/libs ( so it looks like \of_v0.8.4_vs_release\addons\ofxPCL\libs\pcl...  )

-in properties

configuration: all configurations

C/C++ > Additional Include Directories add:
......\addons\ofxPCL\libs\pcl\include;......\addons\ofxPCL\libs\pcl\include\eigen3;......\addons\ofxPCL\libs\pcl\include\pcl-1.7;......\addons\ofxPCL\src;

Linker > General add:
......\addons\ofxPCL\libs\pcl\lib\vs;

Build Events > Post-Build Event:
xcopy /e /i /y "$(PROJECT_DIR)......\addons\ofxPCL\libs\pcl\bin\vs*.dll"  "$(PROJECT_DIR)bin"
xcopy /e /i /y "$(ProjectDir)......\export\vs*.dll" "$(ProjectDir)bin"

configuration: debug
Linker > Input add: 
pcl_common_debug.lib;pcl_features_debug.lib;pcl_filters_debug.lib;pcl_io_debug.lib;pcl_io_ply_debug.lib;pcl_kdtree_debug.lib;pcl_keypoints_debug.lib;pcl_octree_debug.lib;pcl_recognition_debug.lib;pcl_registration_debug.lib;pcl_sample_consensus_debug.lib;pcl_search_debug.lib;pcl_segmentation_debug.lib;pcl_surface_debug.lib;pcl_tracking_debug.lib;qhull.lib;

configuration: release
Linker > Input add: 
pcl_common_release.lib;pcl_features_release.lib;pcl_filters_release.lib;pcl_io_release.lib;pcl_io_ply_release.lib;pcl_kdtree_release.lib;pcl_keypoints_release.lib;pcl_octree_release.lib;pcl_recognition_release.lib;pcl_registration_release.lib;pcl_sample_consensus_release.lib;pcl_search_release.lib;pcl_segmentation_release.lib;pcl_surface_release.lib;pcl_tracking_release.lib;qhull.lib;

**Comment by micuat** [comment]
Hi Paul,

Thanks for the detailed instructions! Unfortunately I'm not actively using PCL these days, but it would be definitely helpful. One thing is that openFrameworks is moving towards version 0.9.0 with VS 2015 support, and I hope your instructions work for VS 2015 as well.
